// Code generated by go-bindata.
// sources:
// db/migrations/1_initial_schema.sql
// db/migrations/2_add_environments_and_repositories.sql
// DO NOT EDIT!

package slashdeploy

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _dbMigrations1_initial_schemaSql = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xd2\xd5\x55\xd0\xce\xcd\x4c\x2f\x4a\x2c\x49\x55\x08\x2d\xe0\x72\x0e\x72\x75\x0c\x71\x55\x08\x71\x74\xf2\x71\x55\x28\x2d\x4e\x2d\x2a\x56\xd0\xe0\x52\x50\xc8\x4c\x51\x28\x49\xad\x28\x51\xf0\xf3\x0f\x51\xf0\x0b\xf5\xf1\x51\x28\x28\xca\xcc\x4d\x2c\xaa\x54\xc8\x4e\xad\xd4\x01\xca\xa7\x67\x96\x64\x94\x26\xc5\x97\xe4\x67\xa7\xe6\x81\x55\x72\x69\x5a\x73\x71\x21\x9b\xed\x92\x5f\x9e\xc7\xe5\x12\xe4\x1f\x80\x6c\xb6\x35\x17\x20\x00\x00\xff\xff\xdb\x4d\x81\xab\x7f\x00\x00\x00")

func dbMigrations1_initial_schemaSqlBytes() ([]byte, error) {
	return bindataRead(
		_dbMigrations1_initial_schemaSql,
		"db/migrations/1_initial_schema.sql",
	)
}

func dbMigrations1_initial_schemaSql() (*asset, error) {
	bytes, err := dbMigrations1_initial_schemaSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "db/migrations/1_initial_schema.sql", size: 127, mode: os.FileMode(420), modTime: time.Unix(1449828966, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _dbMigrations2_add_environments_and_repositoriesSql = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x6c\xce\x41\xcb\x82\x40\x10\xc6\xf1\xfb\x7c\x8a\xe7\xf8\xbe\xa4\x9f\xc0\x93\xe5\x1e\x04\x59\x4b\x5c\xe8\xb6\x08\x0e\xb1\x07\x67\x65\x5d\xca\xbe\x7d\x29\x44\x16\x5d\x67\xe0\xf7\x7f\xd2\x14\xbb\xc1\x5d\x42\x17\x19\x66\xa4\x43\xa3\xf2\x56\xa1\xcd\xf7\x95\x02\xcb\xd5\x05\x2f\x03\x4b\x9c\xf0\x47\x40\xe0\xd1\x4f\x2e\xfa\x70\x47\xe4\x39\x42\xd7\x2d\xb4\xa9\xaa\xe4\xf9\x93\x6e\xe0\xcf\x2b\xfd\x67\xf4\x02\x8d\x2e\x4f\x46\xa1\xd4\x85\x3a\xc3\x49\xcf\xb3\xdd\xea\xd6\x8b\x5d\x70\xdb\x49\x6f\x57\xa9\xd6\x5f\xf9\x77\x3b\x59\x5b\x0b\xbe\x1d\x5f\xf8\x9b\x50\xd1\xd4\xc7\x1f\xe3\x33\x7a\x04\x00\x00\xff\xff\xae\x09\xf4\x66\xe7\x00\x00\x00")

func dbMigrations2_add_environments_and_repositoriesSqlBytes() ([]byte, error) {
	return bindataRead(
		_dbMigrations2_add_environments_and_repositoriesSql,
		"db/migrations/2_add_environments_and_repositories.sql",
	)
}

func dbMigrations2_add_environments_and_repositoriesSql() (*asset, error) {
	bytes, err := dbMigrations2_add_environments_and_repositoriesSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "db/migrations/2_add_environments_and_repositories.sql", size: 231, mode: os.FileMode(420), modTime: time.Unix(1449831661, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"db/migrations/1_initial_schema.sql": dbMigrations1_initial_schemaSql,
	"db/migrations/2_add_environments_and_repositories.sql": dbMigrations2_add_environments_and_repositoriesSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"db": &bintree{nil, map[string]*bintree{
		"migrations": &bintree{nil, map[string]*bintree{
			"1_initial_schema.sql": &bintree{dbMigrations1_initial_schemaSql, map[string]*bintree{}},
			"2_add_environments_and_repositories.sql": &bintree{dbMigrations2_add_environments_and_repositoriesSql, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

